name: sync-mht
github: ekarayel/sync-mht
synopsis: Fast incremental file transfer using Hash-Trees
description: See README at <https://github.com/ekarayel/sync-mht#readme>
author: Emin Karayel <me@eminkarayel.de>
category: Utility
extra-doc-files: README.md
ghc-options: -Wall

library:
  source-dirs: src

default-extensions:
  - DeriveAnyClass
  - DeriveGeneric
  - DerivingStrategies
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - ImplicitParams
  - MultiParamTypeClasses
  - MultiWayIf
  - NoMonomorphismRestriction
  - OverloadedStrings
  - QuasiQuotes
  - RankNTypes
  - ScopedTypeVariables
  - ViewPatterns

dependencies:
  - array >=0.5
  - base >=4.7
  - base16-bytestring >=0.1
  - byteable >=0.1
  - bytes >= 0.15
  - bytestring >=0.10
  - cereal >= 0.4
  - concurrent-extra >= 0.7
  - containers >=0.5
  - cryptohash >=0.11
  - directory >=1.2
  - exceptions >=0.7
  - filepath >=1.3
  - HUnit >= 1.2
  - interpolate >= 0.2
  - io-streams >= 1.2
  - monad-parallel >= 0.7
  - mtl >= 2.1
  - process >= 1.2
  - random >= 1.0
  - regex-compat >= 0.95
  - stm >= 2.5
  - temporary >= 1.2
  - text >=1.1
  - time >= 1.4
  - transformers >= 0.3
  - unix-compat >=0.4
  - zlib >= 0.5
  
executables:
  sync-mht:
    main: Main.hs
    dependencies:
      - sync-mht
    source-dirs: driver

tests:
  unit:
    main: Spec.hs
    verbatim:
      build-tool-depends: sync-mht:sync-mht
    dependencies:
      - sync-mht
      - hspec == 2.*
    source-dirs: test